import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Icon from "./components/Icon/Icon";
import StateProvider from "@/app/context/StateContext";
import SearchInput from "./components/SearchInput/SearchInput";
import Image from "next/image";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className="navbar bg-slate-100 sticky top-0 z-50 dark:bg-slate-800">
					<div className="navbar-start">
						<Link href="/">
							<Image
								priority={true}
								className="dark:hidden"
								alt="Cocktail Wiki"
								src="/logo.svg"
								width={200}
								height={40}
							/>
							<Image
								priority={true}
								className="hidden dark:display"
								alt="Cocktail Wiki"
								src="/logo-dark.svg"
								width={200}
								height={40}
							/>
						</Link>
					</div>
					<div className="navbar-end hidden lg:flex">
						<ul className="menu">
							<li>
								<Link href="/favourites">
									<Icon name="favourite" /> Favourites
								</Link>
							</li>
						</ul>
						<SearchInput />
					</div>
					<div className="navbar-end lg:hidden">
						<ul className="menu menu-horizontal px-1 gap-2">
							<li>
								<Link
									href="/favourites"
									className="btn btn-circle btn-accent text-zinc-50"
								>
									<Icon name="favourite" />
								</Link>
							</li>
						</ul>
						<div className="dropdown dropdown-end lg:hidden">
							<div
								tabIndex={0}
								role="button"
								className="btn btn-circle btn-accent text-zinc-50"
							>
								<Icon name="search" />
							</div>
							<div
								tabIndex={0}
								className="card compact dropdown-content bg-base-100 rounded-box z-[1] w-72 shadow"
							>
								<div tabIndex={0} className="card-body">
									<SearchInput />
								</div>
							</div>
						</div>
					</div>
				</div>
				<StateProvider>{children}</StateProvider>
				<footer className="footer bg-neutral text-neutral-content items-center p-4 mt-12">
					<div className="container mx-auto">
						<aside className="grid-flow-col items-center">
							<p>Copyright © {new Date().getFullYear()} - All right reserved</p>
						</aside>
					</div>
				</footer>
			</body>
		</html>
	);
}
